### ISSUE TITLE
`AttractorsViaProximity` returns inconsistent attractor labels for the same state

### ISSUE THREAD

**Issue by reykboerner** [JuliaDynamics/Attractors.jl#33]
**Describe the bug**
I observe unexpected behavior from `AttractorsViaProximity`. The corresponding `mapper()` function does not return a unique label for a given state when being called repeatedly.

More precisely:
* I define `mapper = AttractorsViaProximity(...)`
* For a point `x`, `mapper(x)` returns `2`
* I call `mapper(y)` for a different state `y`
* I call `mapper(x)` again; now it returns `1`

**Minimal Working Example**
```julia
using DynamicalSystems
using DynamicalSystemsBase
using StaticArrays, LinearAlgebra

# My 2D dynamical system
function fhn(u,p,t)
    x, y = u

    dx = -x^3 + x - y
    dy = -3*y + x

    SVector{2}([dx, dy])
end

ds = ContinuousDynamicalSystem(fhn, [1.,1.], nothing)

# Get the two stable fixed points
box = (-2..2) × (-1..1)
fp, eigs, stable = DynamicalSystems.fixedpoints(ds, box)
attr = Dict(i => Dataset([fp[stable][i]]) for i in 1:2)

mapper = AttractorsViaProximity(ds, attr, 0.05; Δt=0.01, mx_chk_lost=10000)

# Define a state p1 and print its attractor label
p1 = [0.2701377011835575, 1.0]
println("Mapper label of p1: $(mapper(p1))")

# Call the mapper function on a different state
call = mapper(ones(2))

# Reprint the label of p1
println("Mapper label of p1: $(mapper(p1))")
```

The above code outputs the following:

```
Mapper label of p1: 2
Mapper label of p1: 1
```

However, I would expect that "Mapper label of p1" returns the same label every time, since neither the system `ds` nor the state `p1` have been changed. Note that the point p1 lies close to the basin boundary separating the two basins of attraction, but the system is not chaotic, so I don't understand how the same initial condition can land in different attractors.

**Package versions**
```
[61744808] DynamicalSystems v2.3.0
[6e36e845] DynamicalSystemsBase v2.9.1
[90137ffa] StaticArrays v1.5.10
[37e2e46d] LinearAlgebra
```

**Comment by awage** [comment]
Hi! this is a strange bug. 

I solved partially the issue with this: 

```
using DynamicalSystems
using DynamicalSystemsBase
using StaticArrays, LinearAlgebra
using OrdinaryDiffEq:Vern9
# My 2D dynamical system
function fhn(u,p,t)
    x, y = u

    dx = -x^3 + x - y
    dy = -3*y + x

    SVector{2}([dx, dy])
end

ds = ContinuousDynamicalSystem(fhn, [1.,1.], nothing)

# Get the two stable fixed points
box = (-2..2) × (-1..1)
fp, eigs, stable = DynamicalSystems.fixedpoints(ds, box)
attr = Dict(i => Dataset([fp[stable][i]]) for i in 1:2)
diffeq = (;alg = Vern9()) 
mapper = AttractorsViaProximity(ds, attr, 0.05; Δt=0.01, mx_chk_lost=10000, diffeq)

# Define a state p1 and print its attractor label
p1 = [0.2701377011835575, 1.0]
println("Mapper label of p1: $(mapper(p1))")

# Call the mapper function on a different state
call = mapper(ones(2))

# Reprint the label of p1
println("Mapper label of p1: $(mapper(p1))")

```

The output is now consistent. It seems related to a solver issue. But I have no idea why it happens with `SimpleATsit`. Maybe @Datseris has some insight on it.

**Comment by reykboerner** [comment]
Hi, thanks for sharing this quick fix! Good to know that it's probably related to the ODE solver. This helps me a lot for now and I'm happy to keep in touch about further insight.

**Comment by Datseris** [comment]
I think we've encountered similar behavior before. I think there are problems with `reinit!` with the SimpleATsit. Not sure what problems but I think `reinit!` doesn't fully reset some part of the integrator state. But in any case, one shouldn't use this integrator... The reason its the default is because it has a short compile time and low overhead when installing. 

I'll close this for now; one has to identify where is the problem with `reinit!` with the SimpleATsit and open an issue there.
