### ISSUE TITLE
Minimal Fatal Shock search algorithm

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Attractors.jl#4]
In the paper: https://www.nature.com/articles/s41598-020-68805-6

> Minimal fatal shocks in multistable complex networks, Halekotte & Feudel, 2020

The authors discuss a "shock-induced-tipping" and quantifying its resilience via the Minimal Fatal Shock.

The main gist of the idea is in Fig. 1 of the article. 

I think it is possible, and perhaps even simple, to implement an algorithm that computes this for a generic dynamical system in a generic manner.

Inputs should be dynamical system and initial condition u_0 and a function that quantifies the change of attractor (or we use automatic search in basins? I'll need to read the paper in more detail to say more about this function. It is the color coding of the figure below)

**Comment by Datseris** [comment]
There is some code here: https://github.com/halekotte/mifas but I doubt it will be of much help. The code isn't generic enough to be applied in arbitrary dynamical systems. However reading parts of the code will speedup making our own implementation here.

**Comment by Datseris** [comment]
A student wants to apply to implement this in GSoC. I guess he can start wit hthe easy stochastic part and then we can have a meeting to think about the second step.

**Comment by awage** [comment]
Sounds good! If we are not tied to the original implementation we can dig into the ecosystem of Julia package for constrained optimization (`NonConvex.jl` for example). I have a couple of ideas we can explore.
