### ISSUE TITLE
AttractorViaRecurrencies not working

### ISSUE THREAD

**Issue by mdepitta** [JuliaDynamics/Attractors.jl#67]
I have added the `Attractors.jl` package to my Julia 1.8.5. But there are some issues with running it.
The code provided on the [online documentation](https://juliadynamics.github.io/Attractors.jl/dev/examples/#D-basins-via-recurrences) does not work. It produces the error that `basins_of_attraction(mapper)` is incompatible with the sparse version of `AttractorViaRecurrence`. On the online docs, however, it is unclear what method should be used instead of `basins_of_attraction`. 

The full code:

    using Attractors
    using PredefinedDynamicalSystems
    ds = PredefinedDynamicalSystems.thomas_cyclical(b = 0.1665)
    # This computation takes about an hour
    xg = yg = zg = range(-6.0, 6.0; length = 251)
    mapper = AttractorsViaRecurrences(ds, (xg, yg, zg))
    basins, attractors = basins_of_attraction(mapper)
    attractors

The error message:
    ArgumentError: Sparse version of AttractorsViaRecurrences is incompatible with
    `basins_of_attraction(mapper)`.

Package info:

> Status `~/.julia/environments/v1.8/Manifest.toml`
>   [f3fd9213] Attractors v1.5.1
>   [61744808] DynamicalSystems v3.0.0

**Comment by mdepitta** [comment]
It seems that we still need to call `basins_of_attraction(mapper,grid)` to have the above code run. But it is slightly counter-intuitive, why we should pass `grid` both to the `mapper` and the `basins_of_attraction`.

**Comment by mdepitta** [comment]
Another issue that I am clashing against is the following:

My problem is a 4D, and I am passing a grid as a `NTuple{4, Vector{Float64}}`. Could the following error be due to this type of grid?

MethodError: no method matching step(::Vector{Float64})
Closest candidates are:
  step(::LinRange) at range.jl:682
  step(::StepRange) at range.jl:678
  step(::CartesianIndices) at multidimensional.jl:454
  ...

Stacktrace:
  [1] _broadcast_getindex_evalf
    @ ./broadcast.jl:670 [inlined]
  [2] _broadcast_getindex
    @ ./broadcast.jl:643 [inlined]
  [3] (::Base.Broadcast.var"#29#30"{Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, typeof(step), Tuple{NTuple{4, Vector{Float64}}}}})(k::Int64)
    @ Base.Broadcast ./broadcast.jl:1075
  [4] macro expansion
    @ ./ntuple.jl:74 [inlined]
  [5] ntuple
    @ ./ntuple.jl:69 [inlined]
  [6] copy
    @ ./broadcast.jl:1075 [inlined]
  [7] materialize
    @ ./broadcast.jl:860 [inlined]

**Comment by mdepitta** [comment]
It seems so indeed. Then if the only way to pass grids elements is by range(start,stop; length=npts) it could be a serious limitation. There are systems where it is not practical to specify grids by ranges of linearly spaced elements, and it is easier to simply define a Vector and pass it. Is there a workaround for this?

**Comment by Datseris** [comment]
Sparse version means the `sparse` keyword of the `AttractorsViaRecurrences`. You need to use sparse = false.

For the 2nd question, the docs are clear about this: the elements of `grid` must be `AbstractRange` as in-homogeneous grids are not supported yet.

**Comment by Datseris** [comment]
fixed in 700d679
